### ISSUE TITLE
最新版出现wxsid报错

### ISSUE THREAD

**Issue by shangshuaiyu** [hanfangyuan4396/dify-on-wechat#85]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的dify-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

拉取到最新仓库a6a8049038ad5b726bdcb34cda0610a6be15459c
顺利安装所有依赖
python app.py
扫码
报错

### 问题描述 😯

Traceback (most recent call last):
  File "C:\aigc\dify-on-wechat\channel\wechat\wechat_channel.py", line 142, in startup
    itchat.auto_login(
  File "C:\aigc\dify-on-wechat\lib\itchat\components\register.py", line 38, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\aigc\dify-on-wechat\lib\itchat\components\login.py", line 61, in login
    status = self.check_login()
  File "C:\aigc\dify-on-wechat\lib\itchat\components\login.py", line 154, in check_login
    if process_login_info(self, r.text):
  File "C:\aigc\dify-on-wechat\lib\itchat\components\login.py", line 206, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by hanfangyuan4396** [comment]
KeyError: 'wxsid' 需要实名认证
